# -*- coding: utf-8 -*-
"""Saeed_Akhtar_Youtube_channel_qr_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14c-ztTLmsW4VgyM-2sZu2J6oNI_KGXO_
"""

!pip install qrcode

import qrcode as qr

img=qr.make("https://www.youtube.com/channel/UChnXmqDECEdUMneCjpaKHTw")
img.save("Saeed_Akhtar_youtube.png")













import qrcode
from PIL import Image
QR=qr.QRCode(version=1, error_correction=qrcode.constants.ERROR_CORRECT_H,
             box_size=10,border=4, )

QR.add_data("https://www.youtube.com/channel/UChnXmqDECEdUMneCjpaKHTw")
QR.make(fit=True)
img=QR.make_image(fill_color="sienna", back_color="white")
img.save("saeed_youtube_channel.png")

